name: Docker Image CI

on:
  workflow_call:
    inputs:
      build-context:
        description: 'build context'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ inputs.build-context }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.build-context }}
          load: true
          tags: ghcr.io/${{ github.repository }}-${{ inputs.build-context }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Push ${{ inputs.build-context }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.build-context }}
          push: true
          tags: ghcr.io/${{ github.repository }}-${{ inputs.build-context }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max