name: Docker Image push to Github Container Registry

on:
  workflow_call:
    inputs:
      build-context:
        description: 'build context'
        required: true
        type: string
      version:
        description: 'version'
        required: true
        type: string

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ inputs.build-context }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.build-context }}
          load: true
          tags: ghcr.io/${{ github.repository }}-${{ inputs.build-context }}:${{ inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ matrix.platform }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}-${{ inputs.build-context }}:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
      - name: Push ${{ inputs.build-context }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.build-context }}
          push: true
          tags: ghcr.io/${{ github.repository }}-${{ inputs.build-context }}:${{ inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ matrix.platform }}