name: Lint with gradle

on:
  workflow_call:
    inputs:
      java-version:
        description: 'java version'
        required: true
        type: string
      lint-command:
        description: 'lint command'
        required: true
        type: string
      working-directory:
        description: 'working directory'
        required: true
        type: string

jobs:
#  lint-with-super-linter:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: read
#      statuses: write
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Super-Linter
#        uses: github/super-linter/slim@v5
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          VALIDATE_ALL_CODEBASE: true
#          DEFAULT_BRANCH: main
#          FILTER_REGEX_EXCLUDE: gradlew*
#          VALIDATE_JAVA: false
#          VALIDATE_GOOGLE_JAVA_FORMAT: false
  lint-with-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: gradle
      - name: Show Version
        run: |
          java --version
      - name: Gradle lint
        run: ./gradlew ${{ inputs.lint-command }}
        working-directory: ${{ inputs.working-directory }}