name: Lint with Super Linter

on:
  workflow_call:
    inputs:
      lint-mode:
        description: 'lint mode'
        required: true
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter with ${{ github.event.inputs.lint-mode }}
        uses: github/super-linter/slim@v5
        if: ${{ github.event.inputs.lint-mode == 'java-with-gradle' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: gradlew*
          VALIDATE_JAVA: false
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          VALIDATE_SQLFLUFF: false
      - name: Super-Linter with ${{ github.event.inputs.lint-mode }}
        uses: github/super-linter/slim@v5
        if: ${{ github.event.inputs.lint-mode == 'typescript' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_CSS: false