name: Lint with pnpm

on:
  workflow_call:
    inputs:
      node-version:
        description: 'node version'
        required: true
        type: string
      lint-command:
        description: 'lint command'
        required: true
        type: string
      working-directory:
        description: 'working directory'
        required: true
        type: string

jobs:
  lint-with-super-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: github/super-linter/slim@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_CSS: false
  lint-with-pnpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: pnpm
          cache-dependency-path: ./${{ inputs.working-directory }}/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
        working-directory: ${{ inputs.working-directory }}
      - name: Run lint
        run: pnpm ${{ inputs.lint-command }}
        working-directory: ${{ inputs.working-directory }}